name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.turah.my.id"
custom_domain = true
[[routes]]
pattern = "tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.najah.biz.id"
custom_domain = true


[[routes]]
pattern = "tunneling.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.cloudproxyip.my.id"
custom_domain = true

[[routes]]
pattern = "tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.tunneling.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
