name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.turah.my.id"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.najah.biz.id"
custom_domain = true


[[routes]]
pattern = "bzj384jdo.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.cloudproxyip.my.id"
custom_domain = true

[[routes]]
pattern = "bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.bzj384jdo.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
