name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.turah.my.id"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.najah.biz.id"
custom_domain = true


[[routes]]
pattern = "nzi38dkw92.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.cloudproxyip.my.id"
custom_domain = true

[[routes]]
pattern = "nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.nzi38dkw92.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
